In [1]:
import numpy
numpy.__version__

'1.18.1'

In [2]:
import numpy as np

### A Python Integer is More Than Just an Integer

The standard PYthon is written in C, which means that every Python object is simply a cleverly disguised C structre.  So in Python `x = 1000` is no just a raw integer, it has attributes along with it

A single integer contains:

* `ob_refcnt`: A reference count that helps PYthon silently handel memory allocation and deallocation
* `ob_type`:  Which encodes the type of the variable
* `ob_size`:  Which specifies the size of hte following data members
* `ob_digit`:  Which contains the actual integer value that we expect 


### Lists

This is how we create a list of integers

In [3]:
L = list(range(10))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
type(L[0])

int

This is a list of strings

In [6]:
L2 = [str(c) for c in L]
L2

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

Because of Pythons dynamic typing, we can create heterogeneous lists:

In [8]:
L3 = [True, '2', 3.0, 4]
type(L3)

list

In [10]:
[type(item) for item in L3]

[bool, str, float, int]

Because each type is its own object storing all the attributes is not ideal.  Numpy fixes this, and makes for more efficient storing and manitpulating of data

### Fixed Type Arrays in Python


In [11]:
import array
L = list(range(10))
A = array.array('i', L)
A

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Here the 'i' is a type code indeicating the contents are integers,

Numpy is better tho, this is how to create numpy array

In [12]:
import numpy as np
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

Unlike Python lists, numpy is constrained to arrays that all contain the same type.  If they do not match numpy will upcast if possible

In [13]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

If we want to set the data type ourselves, we can use the `dtype` keyword:

In [15]:
np.array([1, 2, 3, 4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

Also numpy arrays can be multidimensional

In [18]:
# nested lists result in multidimensional arrays
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])